services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mern-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    networks:
      - mern-network
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employees
      - PORT=5000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://server:5000
    networks:
      - mern-network
    depends_on:
      - server

networks:
  mern-network:
    driver: bridge
